POST http://localhost:8080/user/register HTTP/1.1
content-type: application/json

{
  "userAccount": "kokota",
  "userPassword": "12345678",
  "checkPassword": "12345678"
}


###
POST http://localhost:8080/user/login HTTP/1.1
content-type: application/json

{
  "userAccount": "kokota",
  "userPassword": "12345678"
}