POST http://localhost:8080/api/user/register HTTP/1.1
content-type: application/json

{
  "userAccount": "kokota",
  "userPassword": "12345678",
  "checkPassword": "12345678"
}


###
POST http://localhost:8080/api/user/login HTTP/1.1
content-type: application/json

{
  "userAccount": "kokota",
  "userPassword": "12345678"
}


###
GET http://localhost:8080/api/user/search?userAccount=kokota HTTP/1.1
content-type: application/json


###
POST http://localhost:8080/api/user/delete HTTP/1.1
content-type: application/json

[
  100
]


###
GET http://localhost:8080/api/user/currentUser HTTP/1.1
content-type: application/json
